### ISSUE TITLE
SWEET32 detection - how to force?

### ISSUE THREAD

**Issue by fool** [adamcaudill/yawast#105]
I'm using v0.5 and while I see in the release notes that several SWEET-related fixes, and in an earlier release that SWEET detection is supported - no scan (using 'scan' or 'head' options) I do actually says anything about sweet.  Was hoping for a pass or fail or not tested - some kind, any kind, of messaging.

Am I missing something?

**Comment by adamcaudill** [comment]
Because the test for SWEET32 is somewhat slow and noisy, it's not enabled by default, you need to specify the `--tdessessioncount` parameter, which can be used with the `ssl` or `scan` commands.

**Comment by fool** [comment]
Thanks Adam!  Worked like a dream.
