### ISSUE TITLE
Add docker container as an runtime option.

### ISSUE THREAD

**Issue by nicksantamaria** [adamcaudill/yawast#119]
I've started a branch adding Docker as a method to install/run YAWAST. https://github.com/nicksantamaria/yawast/tree/docker

This is what I had in mind for the solution:

- A `Dockerfile` to copy source and install dependencies
- Docker-specific usage documentation
- A docker hub account to own the image repository 

A few decisions that must be made:

- Whether to build the container image using the existing Travis CI build ([docs](https://docs.travis-ci.com/user/docker/)), or use docker hub's automated build feature ([docs](https://docs.docker.com/docker-hub/builds/)).
- Which docker hub account should own the repository.

Looking for some guidance from the project maintainer :)

**Comment by adamcaudill** [comment]
Thanks Nick! I've been meaning to do this, I think it's a good idea - so I really appreciate it.

Let me do a little research on the options and I'll get back to you.

**Comment by adamcaudill** [comment]
Nick,

I've setup the Docker hub side: https://hub.docker.com/r/adamcaudill/yawast/

It's setup to build, so it should start working once the Dockerfile is merged in.

**Comment by nicksantamaria** [comment]
Hey @adamcaudill, thanks for getting that sorted. I've created #120, which worked well enough for me, but I haven't factored the 3DES / mbed TLS issues.
