### ISSUE TITLE
SSL Labs integration broken?

### ISSUE THREAD

**Issue by AnotherWayIn** [adamcaudill/yawast#136]
[E] SSL Labs Error: undefined method `each' for nil:NilClass

**Comment by adamcaudill** [comment]
I'm working on something to address this - seems to be happening intermittently. Once I work something out, I'll get a new release out.

(Sorry for the delay in responding - missed the notification for this.)

**Comment by adamcaudill** [comment]
I've made a few changes that should reduce the odds of this happening, but I've not seen this happen in a long time - so I'm going to assume that the issue is resolved. If it comes back, we can reopen this ticket.
