### ISSUE TITLE
Rewrite in Python

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#178]
Given limitations of Ruby, and issues with the current design, YAWAST is being re-written in Python.

Work on the Python conversion is going on in the `dev-python` branch, any changes to the Ruby version will be directed to the `master-ruby` branch. No changes will be made to `master` until #179 is merged.

**Comment by adamcaudill** [comment]
This is for the most part done. We are, for the most part, into final tweaks to get ready for release.

**Comment by adamcaudill** [comment]
Looks like #183 is the last blocker on this ticket.

**Comment by adamcaudill** [comment]
**Release Plan**

- [ ] Deploy 0.8.0bN once all code is ported.
- [ ] Confirm with selected users that the application is working as expected.
- [ ] Release 0.8.0rc1 with any needed fixes.
- [ ] Confirm with a larger group that there are no issues.
- [ ] If issues exist: Correct and release new 0.8.0rcN builds until all reported issues resolved.
- [ ] If no issues: Release 0.8.0

When 0.9.0 is released (target: 2019-09-01), update the Ruby version for a final time to direct users to switch to the Python version (see #186).

**Comment by adamcaudill** [comment]
This is now blocked by #213.

**Comment by adamcaudill** [comment]
@brandonlw I've tagged 0.8.0b6 - can you please build & upload the Windows version?

**Comment by brandonlw** [comment]
It is done.
