### ISSUE TITLE
Report Generation Mode

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#38]
It has been requested that a report generation mode be added (especially useful with #37), to produce easy to read reports, instead of the normal CLI output.

May need to look at building a template (HTML and use replacements to fill in values?) - this would allow users to customize the output to their needs.

**Comment by phlipper** [comment]
JSON output would also be greatly appreciated. Thanks for the tool, and the consideration!

**Comment by adamcaudill** [comment]
I've started work on the JSON output option, finally. I'm not sure if it'll land in the next release, but should be available soon, either way.

**Comment by adamcaudill** [comment]
This isn't done, but many things are now output to a JSON file via the `--output` option.
